services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.1.3"
    ports:
      - 5432:5432
    labels:
      - "com.citusdata.role=Master"
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  worker-1:
    extends:
      file: worker.yml
      service: worker
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - worker-1:/var/lib/postgresql/data

  worker-2:
    extends:
      file: worker.yml
      service: worker
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - worker-2:/var/lib/postgresql/data

  worker-3:
    extends:
      file: worker.yml
      service: worker
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - worker-3:/var/lib/postgresql/data

  worker-4:
    extends:
      file: worker.yml
      service: worker
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - worker-4:/var/lib/postgresql/data

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on:
      - master
    environment: *AUTH

  doku:
    image: "amerkurev/doku"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - "/:/hostroot:ro"
    ports:
      - "9090:9090"

volumes:
  healthcheck-volume:
  worker-1:
  worker-2:
  worker-3:
  worker-4:
